---
- name: Deploy Application
  hosts: api_servers
  gather_facts: no
  tasks:
    - name: Create app directory
      raw: mkdir -p /app/api
    
    - name: Copy application files
      delegate_to: localhost
      raw: docker cp ../app/api/. webserver1:/app/api/
    
    - name: Start Bun application
      raw: cd /app/api && /root/.bun/bin/bun install && /root/.bun/bin/bun run start
